db_url   : 'localhost'
db_type  : 'mysql'
use_mode : 'perform_joins'
database_name : 'tpch_4g'

tables_metadata : 
  table1: 
    name : region
    pk: R_REGIONKEY
    fk: None 
    pja: None
    cja: R_REGIONSID
    r_to: nation_aligned
    r_from: None
  table2: 
    name : nation_aligned
    pk: N_NATIONKEY
    fk: N_REGIONKEY 
    pja: N_REGIONSID
    cja: N_NATIONSID
    r_to: customer_aligned, supplier_aligned
    r_from: region
  table3: 
    name : customer_aligned
    pk: C_CUSTKEY
    fk: C_NATIONKEY 
    pja: C_NATIONSID
    cja: C_CUSTOMERSID
    r_to: orders_aligned
    r_from: None
  table4: 
    name : orders_aligned
    pk: O_ORDERKEY
    fk: O_CUSTKEY 
    pja: O_CUSTOMERSID
    cja: O_ORDERSID
    r_to: lineitem_aligned
    r_from: customer_aligned
  table5: 
    name : 
    pk: R_REGIONKEY
    fk: None 
    pja: None
    cja: R_REGIONSID
    r_to: nation_aligned
    r_from: None
  table6: 
    name : 
    pk: N_NATIONKEY
    fk: N_REGIONKEY 
    pja: N_REGIONSID
    cja: N_NATIONSID
    r_to: customer_aligned, supplier_aligned
    r_from: region
